spring:
  sql:
    init:
      mode: always       # 항상 schema.sql, data.sql 실행
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
