spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB  # 임의로 정한 값 입니다. 크기 조정이 필요 하다면 변경하세요. (S3에 업로드 시 용량 제한하는게 좋습니다)
cloud:
  aws:
    region:
      static: ${AWS_REGION:us-fake-1}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME:fake-bucket-placeholder}
